# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea591f8e4691490b5f27fb8107969068a47f646d3dd0f85634441495df78a142eb23b3b55522113463724fb8843d494ab91016ca5d191c02b1bb3c859895417

test:
  secret_key_base: 9cd169416065412aef557890092c36b806defb608e325cb274be472396450b337fd9c0e172544745e14a460f3b5ff2ef510573514021db07a133d0e989c7d58d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
